set_property PACKAGE_PIN V16 [get_ports a]
set_property PACKAGE_PIN V17 [get_ports b]
set_property PACKAGE_PIN U16 [get_ports z0]
set_property PACKAGE_PIN E19 [get_ports z1]
set_property PACKAGE_PIN U19 [get_ports z2]
set_property PACKAGE_PIN V19 [get_ports z3]
set_property PACKAGE_PIN W18 [get_ports z4]
set_property PACKAGE_PIN U15 [get_ports z5]
set_property PACKAGE_PIN U14 [get_ports z6]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports z0] 
set_property IOSTANDARD LVCMOS33 [get_ports z1] 
set_property IOSTANDARD LVCMOS33 [get_ports z2] 
set_property IOSTANDARD LVCMOS33 [get_ports z3] 
set_property IOSTANDARD LVCMOS33 [get_ports z4]
set_property IOSTANDARD LVCMOS33 [get_ports z5]
set_property IOSTANDARD LVCMOS33 [get_ports z6]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]